### ISSUE TITLE
envenom skill , mutilate rogue

### ISSUE THREAD

**Issue by bl00dm00n** [playAnotherWay/Avalon#1]
Description:
Envenom cost to much energy, and dmg is totaly off
How to reproduce bug:

How it should work:
25 insted of 75, dmg is way to low, its like 5k, should be around 12k
Screenshots:

Relevant AddOns used:
recount
External sources:

Who are you?
zapzapstab

**Comment by bl00dm00n** [comment]
am i doing this right?

**Comment by dasdrifter** [comment]
Envenom costs 35 energy and idk what Envenom you remember but the only way Envenom is hitting ~11k+ is with tons of Attack Power procs, since Envemon scales so hard with Attack Power. 4k Envenoms without procs are standard. If you have all your trinket procs, you might crit 11k with envenom. Might. The Attack Power coefficient is 9% per CP. There's no way it's going to hit for 12k unless you have 11k attack power.
