### ISSUE TITLE
CC overwriting themselves in PvP

### ISSUE THREAD

**Issue by Eltupi** [playAnotherWay/Avalon#118]
Description: If you use the same CC on a target multiple times in PvP it should NOT overwrite the already existing CC effect on the target unless the duration of the new CC-Effect is longer than the one of the already existing one.

How to reproduce bug: Spam Sheep / Fear etc. on any player.

How it should work: The CC should only overwrite itselft once the duration of the new CC-Effect is longer than the one of the already existing one. (For example the 2nd sheep effect should only be applied if the existing sheep has less than 5 seconds left. (because due to Diminishing Return the 2nd sheep is 5 seconds)

Screenshots:  https://www.youtube.com/watch?v=dimnkv0E5YY&feature=youtu.be
An example video (from another Server but its exactly the same here) The first clip is from Rising-Gods (exactly how it works here). THe 2nd one is from old AT how it should work.

Relevant AddOns used: None.

External sources:

Who are you? Eltupi (ingame and on Discord)

**Comment by Eltupi** [comment]
Additional Source: https://youtu.be/EwLOcI4h_kg?t=170
This is video from Retail WoW Season 8.
as you can see at the time stamp at 2:50 going forward the enemy Mage(Daanzka) is sheeping the Rogue (Kalimist). The first sheep gets dispelled but during the 2nd one the Priest (Hydra) is in a kidney shot and therefor cant dispell the Rogue. The Mage (Daanzka) keeps spamming sheeps on the Rogue but the CC-Effect does NOT overwrite itself (aslong as the duration is longer as the one of the new one would be).

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=85I5zuJQIb4 -- Polymorph.
"A more powerful spell is already active"
https://www.youtube.com/watch?v=QHfkeFnqabg&feature=youtu.be&t=135 -- Fear.
"A more powerful spell is already active"
https://www.youtube.com/watch?v=YZzh2MzAfrs&feature=youtu.be&t=6m14s
https://www.youtube.com/watch?v=JwpmJvwgvos&feature=youtu.be&t=118
Both of Entangling Roots/Nature's Grasp.
"A more powerful spell is already active"/not applied (Nature's Grasp charge is still expended though). Sometimes it's because of duration, sometimes it's because of the DoT component of the Root being "weaker" and thus not applying.

This is actually a greater mechanic that affects specific CCs based on duration and/or "potency" (more/less Spell Power/Attack Power, +/-%DMG Buffs/Debuffs etc.) -- it is certain with Fears, Polymorphs and Entangling Roots with certainty -- as well as it affects many Buffs and Debuffs, other DOTs, and many more. I have tons of research on this from before, but there's always a lot to find and confirm, as I have just way too many bookmarks and data, but it's still not enough for all of it.

Edit: @Eltupi you forgot to add your video link off Discord in your extra source. Here it is: https://youtu.be/EwLOcI4h_kg?t=170

Edit 2: **This particular edit is for speculation.**
For example, on the topic of this report for CC overwrites, let's take Stuns.
https://www.youtube.com/watch?v=Wl3Fjns1320&feature=youtu.be&t=279
https://www.youtube.com/watch?v=Wl3Fjns1320&feature=youtu.be&t=362
https://www.youtube.com/watch?v=yczGdP6a8d8&feature=youtu.be&t=8
These all show **different** Controlled Stuns interacting -- first shows Bash > Kidney Shot, second shows Holy Wrath > Bash, third Shows Concussion Blow > Holy Wrath. As can be seen, every second Controlled Stun **exists** but is immediately DR-ed.

I do not yet have evident sources of same-Spell CCs (f.ex. Hammer of Justice instantly into another Hammer of Justice) -- if I did, this might've answered some more questions (logically it would be the same as using Fear > immediate re-Fear -- cast fails at end; would mean f.ex. HoJ > immediate re-HoJ -- HoJ wouldn't be cast, returning the error?).

There is however this:
https://github.com/Atlantiss/BugTracker/issues/6398
> If your target is not past the DR mark (aka 4 seconds) so lets say you just sapped someone and your mashing your freaking sap button and lets say it is at 6 seconds, it should say : A more Powerfull spell is already active.Since its not past the 50% mark (aka 4 seconds).

> If you try to kidney shot someone on a target who has a 6 second kidney shot it should also say the same untill it is @ 3 seconds.

This is useful data corresponding to same-Spell CCs (Kidney Shot VS Kidney Shot, Sap VS Sap, etc. -- logically should return same error, fail to cast, prevent wasting of CD/Debuff application/unnecessary DR-ing).

Snares:
Now this is different -- it's easier.
https://www.youtube.com/watch?v=Wl3Fjns1320&feature=youtu.be&t=226
Notice Earthbind present, Rogue swaps Weapon with Crippling Poison to use Shiv and apply Crippling Poison -- result is CP replaces EB and no other Snares are present anymore. This is due to the fact CP is a 70% Snare -- anything with less Movement Speed reduction would be considered "weaker" and not be cast/applied. **However, Dazes can still be present -- Concussive Shot was still there.**

https://www.youtube.com/watch?v=JwpmJvwgvos&feature=youtu.be&t=73
Chains of Ice + Crippling Poison + Desecrate + Daze (Blade Twisting).
It seems Chains of Ice is an exception -- likely due to the decay to its Snare, making it "dynamic". Desecrate is another exception -- it's a Ground-Target Area of Effect Snare (referred to as GTAoE), similar to others such as Frost Trap -- it seems to be persistent as its own entity(?). Whichever's considered "stronger" takes over. F.ex. initial CoI would be strongest, decaying to/below 70% would make CP "stronger" and take over. Logically, if CP were to fall off and CoI decay below 50%, Desecrate would take over. However, all three exist, as they seem to be "different" in implementation -- it is not the same as Crippling Poison VS Hamstring per se.
Additionally, you can see a Daze in the midst there -- the Rogue attacking placed Savage Combat, meaning it was a Combat Rogue, likely with Blade Twisting (chance to Daze), reaffirming that Dazes are excepted from these rules.

https://www.youtube.com/watch?v=019vZI7gjNw&feature=youtu.be&t=320
This shows Crippling Poison replacing Frostbolt.

Edit 3: Additional source -- see entire report:
https://github.com/ccshiro/cc-buglist/issues/525

I have tons of more sources, but they're about Buffs, Debuffs, DOTs, HOTs etc. -- not quite exactly "CC" so that makes them irrelevant to this report, but still revolving around the "A more powerful spell is already active" gimmick in one way or another.

**Comment by Eltupi** [comment]
@Aridam ty for providing the link i missed.
 But your second Edit is wrong i think. I'm pretty sure that after TBC they changed it so that there could be multiple slows active at the same time (not stacking). The video showig Crippling Poison replacing Frostbolt is from TBC and the ccshiro buglist seems to be from a Vanilla server. This would have been a bug there but is not the case in wotlk anymore.
For example in this frame in the video from WOTLK retail Wow: https://youtu.be/Zf39M7NGFmU?t=168
you can see that 3 different slows are active on the druid:
waylay, Frostbolt, Cripling Poison.

The same is true for stuns: You can have two different named stuns active on the same target at the same time. EDIT: it seems on this point I am wrong. There can apparently only be one stun active on a target. (Watch how at 4:00 the 2nd Cheap Shot effect gets cancel before it ends in favor of a longer Kidney shot. https://youtu.be/Zf39M7NGFmU?t=240 or how the CHeap shot gets cancelled in favor of a longer Deep Freeze here https://youtu.be/_dLUCuebOEU?t=510). Playwise tho this bug is nearly irrelevant as two stuns have the same effect as one does (sometimes magic vs physical makes a difference tho so not completly irrelevant.) This whole discussion tho has nothing to do with the original bug which still is a huge issue.

You also mention that if u cast a CC into the same CC (HoJ -> HoJ or Sap -> Sap) that the cast should fail. Of course the Effect shouldnt apply (the bug we were discussing in the first place) but im pretty confident the animaton of the cast should still come into effect (meaning: mana / energy cost / global cooldown / cooldown on spell). I'm trying to find a source for that but it may be kinda difficult.

**Comment by ghost** [comment]
> But your second Edit is wrong i think. I'm pretty sure that after TBC they changed it so that there could be multiple slows active at the same time (not stacking). The video showig Crippling Poison replacing Frostbolt is from TBC and the ccshiro buglist seems to be from a Vanilla server. This would have been a bug there but is not the case in wotlk anymore.
For example in this frame in the video from WOTLK retail Wow: https://youtu.be/Zf39M7NGFmU?t=168
you can see that 3 different slows are active on the druid:
waylay, Frostbolt, Cripling Poison.

Here're the things that are wrong here.
Slow = effect that slows down Melee Attack Speed/Ranged Attack Speed/Spell Cast Speed.
Snare = effect that shows down Movement Speed.
Two entirely-different CC categories.

Secondly, the correlated issue is from CoreCraft.

Third, in the video you gave, that Frostbolt is there because of [Permafrost](https://wotlk.evowow.com/?spell=12571) -- see the Spells it modifies, as well as check [Frostbolt](https://wotlk.evowow.com/?spell=42842) -- the third effect is added with that Talent. It exists together with Crippling Poison because of that effect. If Crippling Poison overwrote that Frostbolt straight-up, that wouldn't make sense, as it would remove the additional effect of reducing Healing taken, and would be wasted. Additionally, Waylay has a Melee Attack Speed reduction component, as well as a Ranged Attack Speed one -- a Slow. See [here](https://wotlk.evowow.com/?spell=51693) -- it reduces Movement Speed by 50% (Snare) and Melee and Ranged Attack Speeds both by 20% (Slow). The reason Waylay also exists together with Crippling Poison, is so that the Slow component is active on the Target. Crippling Poison is still the strongest Snare, so it's the Snare that is active, while Frostbolt is there for the Healing taken reduction, and Waylay is there for the Melee/Ranged Slow. See Wound Poison being applied -- it removes Frostbolt completely, because CP is the stronger Snare, FB was there for the Healing reduction instead, but WP reduces Healing reduction more, resulting in FB being absolutely useless with no other effect to have -- as a result, it was overwritten completely.

https://www.youtube.com/watch?v=75GUQE-ozo0&feature=youtu.be&t=191
Slow (Snare + Ranged/Spell Slow) + Crippling Poison (Snare) + Waylay (Snare + Melee/Ranged Slow). Crippling Poison has the strongest Snare effect, Slow has the stronger Ranged Slow effect and also a Spell Slow effect, while Waylay has the weaker Ranged Slow and at the same time has a Melee Slow. They are all displayed and are active correspondingly as described, that's why.
[Waylay](https://wotlk.evowow.com/?spell=51693)
[Slow](https://wotlk.evowow.com/?spell=31589)
[Crippling Poison](https://wotlk.evowow.com/?spell=3409)
See each of them and their tables of contents.

The video timestamps showing those Stuns are interesting though -- good finds.
Playwise this is far from irrelevant and is actually important for many possible reasons -- f.ex. to give a couple, because a Physical Stun cannot be Dispelled while a Magic Stun can be, also because Cheap Shot is an Opener Stun while Kidney Shot is a Controlled Stun (two different Stun sub-categories).

> You also mention that if u cast a CC into the same CC (HoJ -> HoJ or Sap -> Sap) that the cast should fail. Of course the Effect shouldnt apply (the bug we were discussing in the first place) but im pretty confident the animaton of the cast should still come into effect (meaning: mana / energy cost / global cooldown / cooldown on spell). I'm trying to find a source for that but it may be kinda difficult.

That's not true -- the reason you fail if you cast Entangling Roots, Fear, Polymorph etc. on a Target with a longer Roots (or stronger DoT to Roots), longer Fear, longer Polymorph, is because when you finish your Cast Time of each Spell, you actually auto-cancel the Spell with the "A more powerful spell is already active", and not cast at all. By your logic, that would mean those Spells should still cast, but not overwrite the "stronger" effect, which isn't the case.

Here are some other examples to back myself up -- they are irrelevant to CCs, but are relevant to not being able to cast something in the first place if its effect is "weaker".
https://www.youtube.com/watch?v=Wl3Fjns1320&feature=youtu.be&t=252
Rogue attempts to overwrite a long SnD with a short one -- gets "A more powerful spell is already active" error and the Ability isn't even cast at all as a result.
https://www.youtube.com/watch?v=43xxTBA2x9Y&feature=youtu.be&t=201
Warlock attempts to overwrite a stronger Corruption with a weaker Corruption, keeps getting the "A more powerful spell is already active" error and it keeps failing to cast (the GCD is cancelled).
**An exception is this: https://www.youtube.com/watch?v=JwpmJvwgvos&feature=youtu.be&t=118 -- because Nature's Grasp is out of the control of the Player, as he is not casting Entangling Roots himself. He gets hit and that triggers NG, spends a charge, but it still doesn't apply the Entangling Roots.**
https://www.youtube.com/watch?v=il7ie38kSwM&feature=youtu.be&t=136
https://www.youtube.com/watch?v=il7ie38kSwM&feature=youtu.be&t=157
https://www.youtube.com/watch?v=il7ie38kSwM&feature=youtu.be&t=206
These show a Warrior trying to refresh a "stronger" Rend with a "weaker" Rend -- in these various timestamps, see his Buffs -- AP procs (Mirror of Truth/Berserking) and +%DMG procs (Enrage, from Wrecking Crew). It returns the same on-screen error and disallows him the casting of Rend in the first place, because his previous Rend that's still ticking is stronger due to Buffs he is missing, making the new Rend weaker, and thus his attempt at clipping it fails, and needs to either wait it out, or get enough Buffs to make it stronger again in order to clip it.

**Edit: It seems your finds with those Stuns are legit. See this: https://www.youtube.com/watch?v=tEH8Au891XM&feature=youtu.be&t=107 -- Shattered Barrier (Random Root) being overwritten by Frost Nova (Controlled Root), because SB ticked down for a short bit, making FN the longer Root, hence "stronger", and as a result, it _completely overwrote_ SB.**

It can be assumed that the Val'kyr in the fight against the Lich King don't fully reflect this mechanic, hence what my finds showed, but yours show the mechanic _properly_ when put in actual **Player versus Player** scenarios.

**Comment by greedman456** [comment]
There exists a bug currently that slow effects stack on top of each other and stack the slow while only the biggest of the lot should be effective. I dont know if this fix caused this
