### ISSUE TITLE
Glitchy tracking/movement bug after hunter's Scatter Shot

### ISSUE THREAD

**Issue by Stingsz** [playAnotherWay/Avalon#17]
Description: I used scatter shot on a rogue but after I used it, the rogues body moved way further than the point from which I scatter shotted him. Once the scatter shot CC was done, his body shot back to the original spot before I scatter shotted him, causing me to fail my trap placement of Freezing Arrow on him during the time he was under the effects of scatter shot.

How to reproduce bug: I asked the rogue to recreate the scenario of which I experienced with a different rogue. I asked him to either use Sprint or Nitro Boots (because that is when I noticed the bug take place)

How it should work: I've seen scatter shot work perfectly. I am not sure why It sometimes works and sometimes It does not. Once the scatter hits, the player takes a few steps in all directions but stays relatively in the same spot. 

Screenshots: N/A

Relevant AddOns used:

External sources: YouTube link to illustrate exactly what the bug is. https://youtu.be/0yYpcjX4zeI 

Who are you? Stingsz, best hunter in Avalon

**Comment by alycai** [comment]
This is what I like to call desync, it happens a lot on private servers.

you will find this kind of pathing/movement bug applies to alot more than just scatter, almost any kind of CC where the target moves (polymorph, blind, fear etc) can produce this kind of desync.

It is also not limited to CC, it can effect charge, feral charge, death grip and knock back effects, where either the target teleports for spells like charge and death grip, or there is a large delay or rubber band type issue much like the video for spells such as blast wave and thunderstorm

**Comment by Stingsz** [comment]
Thank you for the reply!So is there nothing that can be done about this issue?

    On Saturday, December 7, 2019, 05:25:18 PM PST, alycai <notifications@github.com> wrote:  
 
 
This is what I like to call desync, it happens a lot on private servers.

you will find this kind of pathing/movement bug applies to alot more than just scatter, almost any kind of CC where the target moves (polymorph, blind, fear etc) can produce this kind of desync.

It is also not limited to CC, it can effect charge, feral charge, death grip and knock back effects, where either the target teleports for spells like charge and death grip, or there is a large delay or rubber band type issue much like the video for spells such as blast wave and thunderstorm

**Comment by alycai** [comment]
As a PvPer myself I do hope and believe they can be fixed,
it can be incredibly fraustrating to have strange pathing/desync ruin games and matchups.

These kind of issues favour melee the most:
I may use/quote this thread later with more detailed examples of how desync can arise and how it can be abused if you know how to.

One great example is warrior intercept on avalon right now; no matter how hard I tried to force charge to desync I couldnt, but - I've found out that intercept can be desync'd and can be abused:

If you jump away from the target as you intercept you can cause the charge to desync to your opponent, it appear fine on your screen but this is what the opponent sees:

https://streamable.com/9ko5r - observe charge working as you would expect, but notice how the warrior jumps away as he intercepts, causing it to teleport him rather than path him

**Comment by alycai** [comment]
here is bear charge -

https://streamable.com/o9jvs

**Comment by alycai** [comment]
cat charge -

https://streamable.com/fum28

**Comment by Stingsz** [comment]
Wow, thanks for taking the time and sharing with me and replying to me with the details. I really appreciate that!
It's interesting to see the videos and how the bug looks in action from other persepectives!I appreciate all of Another Way Staff's hard work. Thank you all!    On Monday, December 9, 2019, 03:09:55 AM PST, alycai <notifications@github.com> wrote:  
 
 
cat charge -

https://streamable.com/fum28
