### ISSUE TITLE
Forging an alliance

### ISSUE THREAD

**Issue by Burningrosy** [playAnotherWay/Avalon#301]
Description:Bugged quest
The quest "Forging an alliance" does not autocomplete as it should.

How to reproduce bug:

How it should work:So in order to complete this quest you will need to complete the following 2 quests :
1. You Can't Miss Him 
2. Battling the Elements 
I did both which should autocomplete the quest and I should be able to hand it in at Njormeld.
The questionmark is gray and the quest does not complete.

Screenshots: https://prnt.sc/qmlm4z

Relevant AddOns used:

External sources:
https://www.wowhead.com/quest=12924/forging-an-alliance#comments
Who are you?
Burningrose/Nulta

**Comment by ghost** [comment]
Have you tried abandoning and retaking this Quest and going back? Didn't happen to me but I know this issue from the past - - it tends to happen with Quests with required Items. On this occasion, you abandon, retake, and go back to hand in.

Not sure if this is Blizz-like (logically doesn't sound like it), or a legit bug. Gonna have to check.

**Comment by Burningrosy** [comment]
This is actually second time I've tried it, first time I wanted to do it during SOH rep quest chain and then quit cause it didn't work (and I got exalted). This time I was going for all quests in the zone and it didn't work either

**Comment by ghost** [comment]
Odd. Normally that solves the issue. Must be a different problem - - can't see what it _might_ be from that screenshot.

**Comment by ghost** [comment]
Wait, I just noticed something, @Burningrosy. 

Behind your bags, I see what seems to be the objective of bringing Fjorn's Anvil back to Dun Niffelem - - it's gray.

Did you actually do "Battling the Elements" _before_ you took up "Forging an Alliance"? 'Cause if so, that shouldn't even be possible - - I believe that's why you're stuck, since you did Quests out of order you shouldn't have even been able to do as such, so now I guess you need GM assistance to get this sorted, and someone to fix this issue as per this report, so the order is fixed and this is prevented for the future.

Note that I've no idea how it's even possible to have that happen - - I did mine normally and in order, plus I think phasing is proper (unless I missed something). Did you maybe do it and then abandon the Quest after having done it, or something along those lines?

Perhaps the thing with Quests with Items bugging out could've happened after having done it, but the fix through abandoning and retaking doesn't work for this one due to different prerequisites being there, thus missing this objective upon retaking it again - - that part doesn't autocomplete.

Not sure. It's weird.

**Comment by Burningrosy** [comment]
The item you saw was Hodir's spear, for a daily quest, and yes, it might be that I bugged it cause I did it out of order.
Regardless, even without this quest, The Summit of Storm Peaks is doable.
Thanks for the help!
