### ISSUE TITLE
Korogarn Ulduar 25(normal) WAY TOO MUCH DMG

### ISSUE THREAD

**Issue by marcinb12500** [playAnotherWay/Avalon#479]
INSANE DMG on Shockwave and Stonegrip also petrifying breath is not supposed to hit when MT is tanking body

**Comment by mengh3** [comment]
Issue with Stone Grip might be that it's doing damage at the very start of its grabbing animation, instead of when the grabbing animation ends. In the Tankspot video (https://www.youtube.com/watch?v=PSkUlEvZdww) you can see the priest being grabbed at ~1:35, but he didn't start taking damage until the grab animation finished. 

We found that Kolo was using Petrifying Breath when our OT used an AOE taunt to grab adds, while not being in his melee range, which I think might be intended since for a split second his target isn't in melee range.

**Comment by Raydevv** [comment]
Can confirm Stone grip
Shockwave I think you might be talking about a different mechanic for when noone is in melee range of him, didn't occur the 'insane damage'
