### ISSUE TITLE
SHAMAN: Flame shock while Lava Burst is flying.

### ISSUE THREAD

**Issue by martinmarkovic** [playAnotherWay/Avalon#523]
<h3>Description:</h3>

From my past expiriences Lavaburst should crit when flame shock is applied. Here on Avalon, calculation is taking Flame Shock in consideration the moment it starts flying as spell rather then when it hits the target.
That disables the option to cast lavaburst and cast flameshock while lavaburst is flying and to be a 100% critical hit, which it should be by definition of a spell.

<h3>How to reproduce bug: </h3>

Cast lavaburst and apply flameshock while lavaburst is flying.

<h3>How it should work:</h3>

Lavaburst should be 100% crit if flame shock is on target at the moment of hit, rather than moment of fireing a spell.

Screenshots: -

Relevant AddOns used: -

<h3>External sources:</h3>

https://wotlk.evowow.com/?spell=51505

<h3>Who are you?</h3>

Beefboij , Darkiez - ingame
Martinz - Discord

**Comment by ghost** [comment]
That is not a valid source for the actual mechanic.

This mechanic is present for pretty much every Spell, including Projectile Spells, such as Lava Burst - - that is, they snap Stats/Buffs/Debuffs on the Spell finishing the cast, NOT while it's already flying (after it's left the Caster's hand). If it was otherwise, you'd be able to use Shield Wall/Spell Reflection and many other counter-measurements and successfully mitigate such attacks mid-flight, which is definitely not the case.

The only exceptions to this rule are counter-measurements which involve makeshift-"Absorb" (f.ex. Shadowmeld, Vanish, Stealth, Invisibility, Prowl, etc.), or Immune effects (Divine Shield, Ice Block, etc.) - - they act against Spells in mid-flight.
